FROM continuumio/miniconda3
ENV CI=true
ENV PIP_IGNORE_INSTALLED=0

WORKDIR /app

# Create the environment:
COPY polyfun.yml .
RUN conda env create -f polyfun.yml
RUN  conda activate pGWAS
# Make RUN commands use the new environment:
# RUN echo "conda activate pGWAS" >> ~/.bashrc


#install node and npm
ENV NODE_VERSION=16.13.0
RUN apt install -y curl
RUN curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.0/install.sh | bash
ENV NVM_DIR=/root/.nvm
RUN . "$NVM_DIR/nvm.sh" && nvm install ${NODE_VERSION}
RUN . "$NVM_DIR/nvm.sh" && nvm use v${NODE_VERSION}
RUN . "$NVM_DIR/nvm.sh" && nvm alias default v${NODE_VERSION}
ENV PATH="/root/.nvm/versions/node/v${NODE_VERSION}/bin/:${PATH}"
RUN node --version
RUN npm --version


COPY package.json ./

RUN npm install

COPY ./ ./

#remove windows line endings
RUN apt-get install -y dos2unix
RUN dos2unix pipeline_scripts/pipeline.sh
RUN chmod 775 pipeline_scripts/pipeline.sh

CMD [ "npm", "run", "start:dev" ]
